### PR TITLE
Fix iOS keyboard not closing on search

### LINKED ISSUE #517: Pressing search button does not close mobile keyboard
When trying to do a search from iOS, after entering the text, and pressing the return key, no indication of a search being performed is shown, and the keyboard stays open.

I suspect this is because there is no `action` on the form submission.

### PR DESCRIPTION
**Pull request by chris-rudmin**
Fixes #517

### CODE REVIEW

**Comment by chris-rudmin** [comment]
Travis-CI error: `The command "eval npm install  " failed 3 times.`

**Comment by volumio** [comment]
Thanks, very well done!

**Comment by chris-rudmin** [comment]
@volumio Thanks! :) Is there unit tests anywhere to add/update?

**Comment by volumio** [comment]
As weird as it might sound... We do not have unit tests... This is something we're keen to improve, so any help towards this direction is much appreciated

**Comment by chris-rudmin** [comment]
@volumio Will this fix be propagated to the "native" iOS app?

**Comment by volumio** [comment]
Yes, since the app just loads the UI

**Pull request merged**
