### PR TITLE
No drives Alert

### PR DESCRIPTION
**Pull request by apinner**
Added the alert class for the no drives found. Just trying something,
discard if you don't like it.

### CODE REVIEW

**Comment by volumio** [comment]
Mmmm guess the alert is a bit too intrusive.. The important bit is that if we don't receive data, we still show text fields

**Comment by apinner** [comment]
Agreed, I was just thinking of how we could inform them that it didn't automatically discover any shares. I wasn't keen on the plain H3 text, it didn't fit right. 

I was also thinking there will probably be situations in the future when we may want to show an alert type of thing. Leave it with me, i'll style it a bit different and have another look at it. If its not working i'll get rid of it.

**Comment by volumio** [comment]
Perfect!!
Anyway, the text fields should be visible if no NAS has been found, what do you think?

**Comment by apinner** [comment]
I started looking at that but ran out of time before i had to go out. 

We definitely need to fix it and quickly.. I currently cannot listen to any music because i cannot add my windows server share :P

**Pull request merged**
