### PR TITLE
adding french language for UI

### PR DESCRIPTION
**Pull request by balbuze**
french translation for UI
Even with this, plenty of fields are not translated... Maybe not ready in concerned file ?

### CODE REVIEW

**Comment by volumio** [comment]
Thank you! Yes, there are some things still to translate...

**Comment by balbuze** [comment]
I think some small changes will be needed in translation once it will be displayed in Ui because of  specifics French grammar... and context

**Comment by apinner** [comment]
Nice work! This just makes me wish i could speak another language.

**Comment by balbuze** [comment]
But you already speak a language that became nearly universal....

**Comment by apinner** [comment]
Yes, which made the English lazy! We just assume that everyone will speak it, so put no effort into learning anything else and we are worse off for it.

**Pull request merged**
