### PR TITLE
Included Lithuanian language translation

### PR DESCRIPTION
**Pull request by gh201**

### CODE REVIEW

**Comment by volumio** [comment]
Hi, we miss the actual translation files.
Can you provide them?

**Comment by remigijuskastecka** [comment]
I believe it is at https://github.com/volumio/Volumio2-UI/blob/master/src/app/i18n/locale-lt.json, correct me please.
It is in main branch already as translations has been done quite a while ago, using https://translation.volumio.org/projects/volumio/ (tool is currently down, http502)

**Comment by gh201** [comment]
Translation is in the main branch already (https://github.com/volumio/Volumio2-UI/blob/master/src/app/i18n/locale-lt.json)

**Comment by volumio** [comment]
Thanks!

**Pull request merged**
