### PR TITLE
Touchicons

### PR DESCRIPTION
**Pull request by apinner**

### CODE REVIEW

**Comment by apinner** [comment]
Something wrong with this PR?

**Comment by volumio** [comment]
I just tested it, and it breaks the dynamic favicon (it says the same no matter what the playback state is...)
As soon as you can solve it I'll merge it!!!

**Comment by apinner** [comment]
Weird.. i tested it and the dynamic favicon worked. Which browser was that?

**Comment by apinner** [comment]
@volumio You were right, it wasn't working at all! Pretty sure i've now fixed it and i've tested it on desktop and android.

**Pull request merged**
