### PR TITLE
Issue 258

### PR DESCRIPTION
**Pull request by earlchew**

### CODE REVIEW

**Comment by likeitneverwentaway** [comment]
@volumio Can you please have a look at this one ? This will allow users to use Volumio alongside other web applications which would be great! Is there anything retaining you from merging ? 

Thanks!

**Comment by volumio** [comment]
@likeitneverwentaway yep, there are conflicts and we're in the middle of a UI rework. Unfortunately this won't be merged

**Comment by earlchew** [comment]
@volumio Are the merge conflicts the only issue, or are there other concerns?

**Comment by earlchew** [comment]
@volumio I had a look at the conflicts, and I think the resolution is fairly straightforward.

Is there anything else that is a concern?

**Comment by volumio** [comment]
@earlchew yes, basically the player endpoint chaning logic has been removed with your commits. On the other hand, we're working behind the curtains to offer the ability to reach any volumio device securely from outside. It's a big rework, and it will make this PR obsolete.
Can't merge...

**Pull request closed without merging**
