### PR TITLE
Correctly scale non-square library cover images

### PR DESCRIPTION
**Pull request by davidcole1977**
I thought I'd start contributing with a very small, safe change before I jump into some much larger, more impactful PRs.

Fixes a minor UI glitch that causes folder/track/artist thumbnail images to be displayed stretched to the wrong proportions when a non-square image is used.

The solution is a very simple CSS update that will cause non-square images to be scaled with correct proportions, cropping the image instead of stretching it. `object-fit` is supported in most browsers, but browsers that don't support it will simply ignore the new CSS rule. (See the [CSS Tricks article](https://css-tricks.com/almanac/properties/o/object-fit/) for more about this CSS rule)

**Before:**

thumbnail-fix-before

**After:**

thumbnail-fix-after

### CODE REVIEW

**Comment by davidcole1977** [comment]
I noticed the CI build is failing. From the logs, it looks like this is common to a lot of PRs and appears to be an issue with the build script and not the commits in this PR.

**Comment by volumio** [comment]
Thank you very much! Very sensible

**Comment by davidcole1977** [comment]
Nice one! That was super fast - thanks :)

**Comment by volumio** [comment]
To you! Looking forward to see what you will come up with next ;)

**Pull request merged**
