### PR TITLE
header opacity fix

### PR DESCRIPTION
**Pull request by apinner**
my fix for the issue when overlapping two opaque divs for the rounded play button. Also replaced the logo for a light version for the darker header.

### CODE REVIEW

**Comment by volumio** [comment]
I just love it... However I think the thin border on time control and volume control are not good for usability... Could you please set them as they were before? 
Also, the file type should be at the bottom on the time circle...
Looks really amazing!

**Comment by apinner** [comment]
Just to counter what you say.. the thinner border on the dials doesn't really effect usability as much as you think. The entire knob remains click and touchable. It's not like you need to click the thin line, anywhere on the knob pretty much will work.

**Comment by kurtommy** [comment]
Hi @apinner i cherry picked your good stuff, for the future, use .editorconfig (spaces instead tabs) and respect indentation rules.
From now on submit PR for development branch not master.

Many thanks

**Comment by apinner** [comment]
@kurtommy that's absolutely fine. Apologies it wasn't very tidy, I really was just hacking away it was by no means meant for release.

**Pull request closed without merging**
