### PR TITLE
Spanish Translation

### PR DESCRIPTION
**Pull request by mundodisco8**
Added the Spanish translation file and modified index.config.js

I wasn't able to create a build environment and test it thoroughly, but I think 99% of it it's OK. This would have been great in order to test it in mobile, to check for text overflows.

Some of the constructed phrases (as "NAS was mounted successfully") might be in broken spanish and need a retouch. Also, there is one or two words that I couldn't find in the interface and I had to guess the context of their meaning, I hope I guessed right.

### CODE REVIEW

**Comment by apinner** [comment]
Thank you @mundodisco8 

One thing, can you please fix the indentation in index.config.js

https://github.com/mundodisco8/Volumio2-UI/blob/1010cbf9387c4879236c339f3ca91bb91f7363eb/src/app/index.config.js#L28

You need to use two spaces rather than a tab.

**Comment by volumio** [comment]
Muchas gracias tio! 
Alex, I'm fixing that, thanks for pointng out...

**Comment by mundodisco8** [comment]
My silly notepad++ was in tab mode, I thought it was in space mode.

**Comment by apinner** [comment]
Muy Bien!

Look at that.. My grade E Spanish GCSE paying off!

**Pull request merged**
