### PR TITLE
Add sleep timer presets dropdown.

### PR DESCRIPTION
**Pull request by teq0**
I previously did a PR for adding sleep timer preset values using small buttons but the suggestion was that it didn't match the rest of the UI and that a dropdown would be more appropriate, so here it is.

It also sets the enabled button if the user selected a time, and resets it if they picked "Off", which saves an extra button click.

### CODE REVIEW

**Comment by teq0** [comment]
This appears to have failed because of rate limiting on the npm API, nothing actually to do with my PR. Can someone please run the build again?

**Comment by volumio** [comment]
Well done! 
Just 2 details to make it perfect:
1- We should have the strings translatable (mins, off, ecc).
2- As placeholder I will put something like 1 hour (translatable)

what do you think?

**Comment by teq0** [comment]
Agree that text needs translation, but I can only do the English (which assume it will default to until someone can fill in some other languages).

But I think the placeholder text shouldn't suggest that a value has already been selected, it needs to make it clear that you need to click to select a value. I tried "Select preset" but it can be too wide for some device form factors.

Also, the build appears to be failing because of some dependency, or something, nothing to do with my changes. What should I do?

**Comment by volumio** [comment]
Very good, thanks!

**Pull request merged**
